// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3YEERFhcdsOR3EPKp8SniJWw3wM8zQug',
    appId: '1:910336516046:android:c7cf84dc1f189ade5a559f',
    messagingSenderId: '910336516046',
    projectId: 'dao-culture-app',
    storageBucket: 'dao-culture-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCByErFZ5IdxzAobE12ykUCLqg0PlgVddw',
    appId: '1:910336516046:ios:6f3d6fb27fc2eba35a559f',
    messagingSenderId: '910336516046',
    projectId: 'dao-culture-app',
    storageBucket: 'dao-culture-app.firebasestorage.app',
    iosBundleId: 'com.example.daoCultureApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNfPa0Mf7hAyXDbBB1j4FpUQYWAl-FHsI',
    appId: '1:910336516046:web:a3ad9a45f420b4c75a559f',
    messagingSenderId: '910336516046',
    projectId: 'dao-culture-app',
    authDomain: 'dao-culture-app.firebaseapp.com',
    storageBucket: 'dao-culture-app.firebasestorage.app',
    measurementId: 'G-JXP26L5TRS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCByErFZ5IdxzAobE12ykUCLqg0PlgVddw',
    appId: '1:910336516046:ios:6f3d6fb27fc2eba35a559f',
    messagingSenderId: '910336516046',
    projectId: 'dao-culture-app',
    storageBucket: 'dao-culture-app.firebasestorage.app',
    iosBundleId: 'com.example.daoCultureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNfPa0Mf7hAyXDbBB1j4FpUQYWAl-FHsI',
    appId: '1:910336516046:web:8ee331bc015862305a559f',
    messagingSenderId: '910336516046',
    projectId: 'dao-culture-app',
    authDomain: 'dao-culture-app.firebaseapp.com',
    storageBucket: 'dao-culture-app.firebasestorage.app',
    measurementId: 'G-F4JGSQWTNE',
  );

}